name = "cfw-raft"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "11ff2e53fe4b55488bb282adbe0789b6"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-17"

[build]
command = "npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
    {name = "memberActor", class_name = "MemberActor"},
    {name = "clusterActor", class_name = "ClusterActor"},
]

[[migrations]]
tag = "v1"
new_classes = ["MemberActor", "ClusterActor"]
